export const allowedPermissions = [
  'business:update',
  'members:invite',
  'members:remove',
  'members:update_role',
  'members:update_status',
  'members:view',
  'roles:view',
  'roles:create',
  'roles:update',
  'roles:delete',
  'roles:assign',
  'payments:create',
  'payments:view',
  'payments:view_own',
  'payments:approve',
  'payments:cancel',
  'providers:create',
  'providers:update',
  'providers:view',
  'invoices:create',
  'employee_lists:create',
  'employee_lists:view',
  'employee_lists:update',
  'employee_lists:archive',
  'employees:create',
  'employees:view',
  'employees:update',
  'employees:archive',
  'employees:verify',
  'invoices:view',
  'reports:view',
  'audit_logs:view',
  'employees:view_own',
  'policies:view',
  'policies:create',
  'policies:update',
  'policies:archive',
  'policies:assign',
  'policies:view_audit',
  'policies:reconcile',
  'integrations:view',
  'integrations:manage',
] as const;

export type Permission = (typeof allowedPermissions)[number];

export const systemRolePermissions = {
  owner: [...allowedPermissions],
  admin: [
    'members:invite',
    'members:view',
    'members:update_status',
    'payments:create',
    'payments:approve',
    'payments:view',
    'providers:create',
    'providers:update',
    'invoices:create',
    'invoices:view',
    'reports:view',
    'audit_logs:view',
    'employee_lists:create',
    'employee_lists:view',
    'employee_lists:update',
    'employee_lists:archive',
    'employees:create',
    'employees:view',
    'employees:update',
    'employees:archive',
    'employees:verify',
    'integrations:view',
    'integrations:manage',
  ],
  finance_manager: [
    'payments:create',
    'payments:approve',
    'payments:view',
    'providers:create',
    'invoices:create',
    'invoices:view',
    'reports:view',
    'employee_lists:create',
    'employee_lists:view',
    'employee_lists:update',
    'employees:create',
    'employees:view',
    'employees:update',
    'employees:verify',
    'members:view',
  ],
  accountant: [
    'payments:view',
    'invoices:view',
    'reports:view',
    'members:view',
    'employee_lists:view',
    'employees:view',
  ],
  employee: [
    'employees:view_own',
    'members:view',
    'employee_lists:view',
    'reports:view',
  ],
  contributor: ['payments:create', 'members:view', 'payments:view_own'],
  viewer: ['payments:view', 'invoices:view', 'members:view', 'reports:view'],
} satisfies Record<string, Permission[]>;

export type SystemRoleKey = keyof typeof systemRolePermissions;
export const systemRoleDeniedPermissions: Record<SystemRoleKey, Permission[]> =
  {
    owner: [],
    admin: [],
    finance_manager: [],
    accountant: [],
    employee: [],
    contributor: [],
    viewer: [],
  };

export function effectivePermissions(
  grants: readonly Permission[],
  denials: readonly Permission[],
): Permission[] {
  const denied = new Set(denials);
  return [...new Set(grants)].filter((permission) => !denied.has(permission));
}
